### PR TITLE
WIP raw msg/bigarray support

### PR DESCRIPTION
**Pull request by hcarty**
I want to add `recv_msg_all` and `send_msg_all` functions before a merge, but for anyone interested the core functionality is here for sending and receiving bigarrays.

A simplistic echo client/server pair are included as an example.

Addresses #27

### CODE REVIEW

**Comment by andersfugmann** [comment]
Thanks for the PR. 

If I read this correctly the caml_zmq_recv_msg function avoids copying data by returning the data directly from zmq message data structure, and registers a finalizer function. I would think the same approach could be used by caml_zmq_recv. There is a comment about message lifetime, but I cannot find this in the zmq documentation. Can you provide a link to this?

The send function still copies the data from the bigarray to a zmq_msg, so using a bigarray still copies the data the same amount of times as before. 

Can you motivate why this patch provides a speedup in the send case? I can only see that using bigarrays might be faster than regular sting when sending very large data structures. For small messages, the messages would be created in the minor heap which I assume is just as cheap as using bigarrays.




However the code 

As for the send function, 

The send function

**Comment by hcarty** [comment]
You are correct - `caml_zmq_msg_recv` does not copy the content within the `zmq_msg_t` value.  A similar approach could be used with `caml_zmq_recv`.   It may be worth providing a `string`-returning version of `Msg.copy_data` so that the `Msg` module can act as a lower-level functional equivalent to `caml_zmq_recv`.

For message lifetimes, see entries like http://api.zeromq.org/4-2:zmq-msg-init-data (deallocation function will be called when the data buffer is no longer required by zeromq) and http://api.zeromq.org/4-2:zmq-msg-close (states that `zmq_msg_close` tells zeromq that a `zmq_msg_t` can be freed but it doesn't specify that all of its content must be freed immediately) and http://zeromq.org/blog:zero-copy (discussion of "zero-copy" messages with zeromq).

`send_msg` doesn't copy the bigarray content, aside from any copying zeromq may do internally.  `Msg.init_data` does not copy the bigarray.  `zmq_msg_init_data` uses the physical pointed-to bytes.  It does not copy the message content.

While the lack of copying may be useful in many cases, I have two primary use-cases for where the extra complexity of using bigarrays would be worthwhile.  One is a high-throughput proxy which may add/remove/manipulate pieces of multi-part messages.  The other is for large messages, in the 10s to 100s of megabytes range.  Those large messages would benefit from the lack of copying when sent in full.  These large messages could also be efficiently chunked into multiple messages without copying by specifying appropriate offsets and lengths when creating messages to send.

**Comment by hcarty** [comment]
@andersfugmann ping?

**Comment by hcarty** [comment]
@andersfugmann ping

**Comment by andersfugmann** [comment]
Is this still relevant? I think its safe to merge, once rebased on master.

**Comment by Leonidas-from-XIV** [comment]
Rebased in #53.

**Pull request closed without merging**
