### PR TITLE
Use c99 types for 64bit integers (fix compilation w. 4.03)

### PR DESCRIPTION
**Pull request by andersfugmann**
This allows compilation using ocaml 4.03+trunk (opam version), and does not break build for 
ocaml < 4.03.

However, tests hangs under 4.03 but not with 4.02.3.

### CODE REVIEW

**Comment by copy** [comment]
[This](https://github.com/issuu/ocaml-zmq/blob/master/test/zmq_test.ml#L209) is the line that causes the hang.

**Comment by UnixJunkie** [comment]
Now we know; should this be merged ?

**Comment by hcarty** [comment]
Does the hang still happen after the move to the stdint library?

**Comment by andersfugmann** [comment]
I've tracked down the hang in the test. It would seem that the context is closed by the finaliser before the finalizer is called on the socket, even though the socket references the context. This causes:
1. Finalizing the socket if there are lingering messages on open socket will hang.
2. Finalizing a socket _after_ the context has been closed will cause a crash

The documentation on Gc.finalise seems to indicate that contexts (which are registered first) will be finalized before sockets. If this is indeed true, the library has a serious problem wrt. running finalizers, and I'm inclined to just remove all finalisers from ZMQ, leaving it up to the developer to release resources manually.

As this patch does indeed solve compilation with 4.03 and tests are now working I'm ready to merge it. However I'd like to hear if anyone has an opinion on the finaliser issue first.

**Comment by UnixJunkie** [comment]
If a developer has acquired resources manually, I think it is fine to ask him to also release them manually.

**Comment by hcarty** [comment]
While I'm ok with requiring users to free resources manually (and it makes sense for something like sockets!), it would be nice from a catching-user-errors perspective if sockets and contexts warned users if the finalizer was called before a socket/context was properly closed.

The simplest way to do this may be to change the socket internal representation so it references the parent context.

**Comment by andersfugmann** [comment]
Ok. I will change the code to not release resources through finalisers. The finalisers will still warn (on stderr for now) if the user forgets to release resources. 

Later I can add proper resource deallocation strategy through finalisers in ocaml-land rather than in C-land which is (to me at least) harder to maintain.

**Pull request merged**
